kind: Deployment
apiVersion: apps/v1beta2

metadata:
  name: vault-controller
  namespace: {{ .Values.Namespace | quote }}
  labels:
{{ include "pkg.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-controller
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/vault-secret.yaml") . | sha256sum }}
      labels:
        app: vault-controller
    spec:
      containers:
        - name: vault-controller
          image: {{ .Values.Image }}
          command:
            - /kube-vault-controller
            - --sync-period={{ .Values.SyncPeriod }}
            - --namespace={{ .Values.WatchNamespace }}
            - --saauth={{ .Values.ServiceAccountAuth }}
            - --vaultauth={{ .Values.VaultAuth }}
            - --vaultrole={{ .Values.VaultRole }}
          env:
            - name: VAULT_ADDR
              value: {{ .Values.VaultAddress | quote }}
{{- if not .Values.ServiceAccountAuth }}
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: vault-token
                  name: {{ .Values.VaultSecret | quote }}
{{- end }}
{{- if .Values.VaultClientSkipTLSVerify }}
            - name: VAULT_SKIP_VERIFY
              value: 1
{{- end }}
{{- if .Values.VaultClientRateLimit }}
            - name: VAULT_RATE_LIMIT
              value: {{ .Values.VaultClientRateLimit }}
{{- end }}
{{- if .Values.VaultClientRetries }}
            - name: VAULT_MAX_RETRIES
              value: {{ .Values.VaultClientRetries }}
{{- end }}
