{{- if not .Values.ServiceAccountAuth }}
kind: Secret
apiVersion: v1

metadata:
  name: {{ .Values.VaultSecret | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pkg.labels" . | indent 4 }}
type: Opaque
data:
  vault-token: {{ .Values.VaultToken | b64enc | quote}}
{{- end }}
